version: '3.8'

services:
  ioquake3-server:
    image: florianpiesche/ioquake3-server:latest
    container_name: ioquake3-server
    restart: unless-stopped
    ports:
      - "27960:27960/udp"
    environment:
      - ARGS=+set fs_game baseq3 +set ded_lan 0 +set net_port 27960
    volumes:
      - ioquake3_data:/usr/local/games/quake3/baseq3

volumes:
  ioquake3_data:
