version: '3.8'

services:
  xonotic-server:
    image: lscr.io/linuxserver/xonotic:latest
    container_name: xonotic-server
    restart: unless-stopped
    ports:
      - "26000:26000/udp"
      - "26000:26000/tcp"
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - xonotic_data:/config

volumes:
  xonotic_data:
