version: '3.8'

services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    environment:
      - TZ=Etc/UTC
      - PUID=1000
      - PGID=1000
    ports:
      - "0.0.0.0:13378:80"
    volumes:
      - audiobookshelf_config:/config
      - audiobookshelf_metadata:/metadata
      - /opt/audiobookshelf/audiobooks:/audiobooks
      - /opt/audiobookshelf/podcasts:/podcasts
    restart: unless-stopped

volumes:
  audiobookshelf_config:
  audiobookshelf_metadata:
