version: '3.8'

services:
  aoe2de-server:
    image: ich777/ageofempires2de:latest
    container_name: aoe2de-server
    restart: unless-stopped
    ports:
      - "27020:27015/udp"
      - "27021:27016/udp"
    environment:
      - GAME_PORT=27020
      - QUERY_PORT=27021
    volumes:
      - aoe2de_data:/serverdata

volumes:
  aoe2de_data:
